'use strict';
const $=id=>document.getElementById(id);
const STYLES=[['aurora','✧','Aurora'],['waves','≋','Waves'],['orbs','◉','Orbs'],['mesh','▨','Mesh'],['ribbons','〰','Ribbons'],['mountains','△','Hills'],['rings','◎','Rings'],['stars','✦','Stars'],['glass','◇','Glass']];
const PALETTES=[['#6d5dfc','#ef79a3','#132d5c'],['#00c6a9','#087cbb','#041a46'],['#ff9b71','#e8498a','#34105b'],['#f6bd60','#ed6a5a','#372b66'],['#c8fcf3','#89a6f7','#33366c'],['#ffc8dd','#bde0fe','#4b4d85'],['#f5f7fa','#aebbd3','#28334d'],['#1d2671','#c33764','#090b25'],['#b1e3b0','#23a6a6','#132848'],['#fae18e','#fb918b','#6454a4']];
const DEFAULT={style:'aurora',colors:[...PALETTES[0]],preset:'1080x2400',width:1080,height:2400,detail:55,glow:55,rotation:0,seed:123456};
let state={...DEFAULT,colors:[...DEFAULT.colors]};let renderId=0;let previewTimer;const cvs=$('preview');const cx=cvs.getContext('2d',{alpha:false});
function rng(seed){let s=seed>>>0;return ()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296}}
function hex(c){let s=c.replace('#','');return [0,2,4].map(i=>parseInt(s.slice(i,i+2),16))}function rgba(c,a){let v=hex(c);return `rgba(${v[0]},${v[1]},${v[2]},${a})`}
function mix(a,b,t){let x=hex(a),y=hex(b);return '#'+x.map((v,i)=>Math.round(v*(1-t)+y[i]*t).toString(16).padStart(2,'0')).join('')}
function grad(ctx,w,h,colors){let g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,colors[2]);g.addColorStop(.52,mix(colors[2],colors[0],.60));g.addColorStop(1,mix(colors[1],colors[2],.43));ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
function blob(ctx,x,y,r,color,opacity=1){let g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,rgba(color,opacity));g.addColorStop(.34,rgba(color,opacity*.44));g.addColorStop(1,rgba(color,0));ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2)}
function draw(canvas,s){const ctx=canvas.getContext('2d',{alpha:false});const w=canvas.width,h=canvas.height,ref=Math.min(w,h),random=rng(s.seed),d=s.detail/100,soft=s.glow/100,cols=s.colors;ctx.save();grad(ctx,w,h,cols);ctx.translate(w/2,h/2);ctx.rotate(s.rotation*Math.PI/180);ctx.translate(-w/2,-h/2);
 if(s.style==='aurora'){for(let k=0;k<7+Math.floor(d*6);k++){let x=random()*w,y=random()*h,r=ref*(.35+random()*.85);blob(ctx,x,y,r,cols[k%2],.19+soft*.29)}for(let j=0;j<4+Math.round(d*4);j++){let y=h*(.1+random()*.8),amp=ref*(.06+random()*.15);ctx.beginPath();ctx.moveTo(-w*.5,y);for(let x=-w*.5;x<=w*1.5;x+=Math.max(8,w/130)){let yy=y+Math.sin(x/w*6+j*.9)*amp+Math.sin(x/w*12+j)*amp*.25;ctx.lineTo(x,yy)}ctx.strokeStyle=rgba(cols[j%2],.12+soft*.18);ctx.lineWidth=ref*(.025+soft*.045);ctx.lineCap='round';ctx.stroke()}}
 if(s.style==='waves'||s.style==='ribbons'){let n=s.style==='waves'?8+Math.round(d*24):5+Math.round(d*12);for(let i=0;i<n;i++){let y=h*(i+.4)/n;ctx.beginPath();for(let x=-w*.3;x<=w*1.3;x+=Math.max(5,w/170)){let yy=y+Math.sin((x/w)*7.5+i*.38+s.seed*.000002)*ref*(s.style==='waves'?.12:.22)+Math.sin(x/w*16+i)*ref*.025;if(x===-w*.3)ctx.moveTo(x,yy);else ctx.lineTo(x,yy)}ctx.strokeStyle=rgba(cols[i%3],s.style==='waves'?.36:.46);ctx.lineWidth=ref*(s.style==='waves'?.012:.05)*(1+soft*.7);ctx.lineCap='round';ctx.stroke()}}
 if(s.style==='orbs'){for(let i=0;i<12+Math.round(d*27);i++){let x=random()*w,y=random()*h,r=ref*(.04+random()*.3);blob(ctx,x,y,r,cols[i%3],.27+soft*.7);ctx.beginPath();ctx.arc(x,y,r*.35,0,Math.PI*2);ctx.fillStyle=rgba(cols[i%3],.04+soft*.13);ctx.fill()}}
 if(s.style==='mesh'){let sz=ref/(5+Math.round(d*19));ctx.lineWidth=Math.max(1,ref*.0015);for(let x=-w;x<2*w;x+=sz){ctx.beginPath();for(let y=-h;y<2*h;y+=6){let vx=x+Math.sin(y/ref*5+x/ref*3+s.seed*.00001)*sz*.35;if(y===-h)ctx.moveTo(vx,y);else ctx.lineTo(vx,y)}ctx.strokeStyle=rgba(cols[0],.15+soft*.3);ctx.stroke()}for(let y=-h;y<2*h;y+=sz){ctx.beginPath();for(let x=-w;x<2*w;x+=6){let vy=y+Math.sin(x/ref*4+y/ref*2)*sz*.3;if(x===-w)ctx.moveTo(x,vy);else ctx.lineTo(x,vy)}ctx.strokeStyle=rgba(cols[1],.11+soft*.28);ctx.stroke()}}
 if(s.style==='mountains'){let n=4+Math.round(d*8);for(let i=0;i<n;i++){let base=h*(.27+i*.8/n),offset=random()*9;ctx.beginPath();ctx.moveTo(-w*.4,h*1.4);for(let x=-w*.4;x<=w*1.4;x+=Math.max(6,w/110)){let y=base+Math.sin(x/w*6+offset)*ref*(.06+i*.006)+Math.sin(x/w*12+offset*2)*ref*.025;ctx.lineTo(x,y)}ctx.lineTo(w*1.4,h*1.4);ctx.closePath();ctx.fillStyle=mix(cols[i%3],cols[2],.4+i/n*.3);ctx.globalAlpha=.75;ctx.fill();ctx.globalAlpha=1}}
 if(s.style==='rings'){for(let i=0;i<8+Math.round(d*26);i++){let x=random()*w,y=random()*h,r=ref*(.04+random()*.54);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.strokeStyle=rgba(cols[i%3],.10+soft*.47);ctx.lineWidth=ref*(.002+random()*.013);ctx.stroke()}}
 if(s.style==='stars'){let n=60+Math.round(d*480);for(let i=0;i<n;i++){let x=random()*w,y=random()*h,r=ref*(.0005+random()*.004);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=rgba(i%4===0?cols[1]:'#ffffff',.25+random()*.7);ctx.fill()}for(let i=0;i<8;i++)blob(ctx,random()*w,random()*h,ref*(.12+random()*.35),cols[i%2],.17+soft*.24)}
 if(s.style==='glass'){for(let i=0;i<9+Math.round(d*15);i++){let rw=ref*(.15+random()*.56),rh=ref*(.18+random()*.7),x=random()*w-rw/2,y=random()*h-rh/2,r=ref*.04;ctx.beginPath();ctx.roundRect(x,y,rw,rh,r);ctx.fillStyle=rgba(cols[i%3],.06+soft*.14);ctx.fill();ctx.strokeStyle=rgba('#ffffff',.08+soft*.25);ctx.lineWidth=Math.max(1,ref*.002);ctx.stroke()}for(let i=0;i<5;i++)blob(ctx,random()*w,random()*h,ref*.35,cols[i%2],.18)}
 ctx.restore();}
function size(){return [Math.min(7680,Math.max(256,+state.width||1080)),Math.min(7680,Math.max(256,+state.height||2400))]}
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').style.display='none',2600)}
function updateControls(){document.querySelectorAll('.stylebtn').forEach(b=>{b.classList.toggle('active',b.dataset.style===state.style);b.setAttribute('aria-pressed',String(b.dataset.style===state.style))});document.querySelectorAll('.palette').forEach(b=>b.classList.toggle('active',b.dataset.index==PALETTES.findIndex(p=>p.every((v,i)=>v===state.colors[i]))));[1,2,3].forEach((n,i)=>$('color'+n).value=state.colors[i]);$('preset').value=state.preset;$('customSize').classList.toggle('hidden',state.preset!=='custom');$('width').value=state.width;$('height').value=state.height;for(let key of ['detail','glow','rotation']){$(key).value=state[key];$(key+'Value').textContent=state[key]+(key==='rotation'?'°':'%')}const [w,h]=size();$('resolution').textContent=`${w} × ${h}`}
function preview(){const [w,h]=size();let scale=Math.min(1,1000/Math.max(w,h));cvs.width=Math.round(w*scale);cvs.height=Math.round(h*scale);draw(cvs,state);$('description').textContent=`${STYLES.find(t=>t[0]===state.style)[2]} · Seed ${state.seed} · locally generated`;$('status').textContent='Ready'}
function refresh(){updateControls();clearTimeout(previewTimer);previewTimer=setTimeout(preview,55)}
function newSeed(){state.seed=Math.floor(Math.random()*4294967295);refresh()}
function init(){STYLES.forEach(([id,icon,name])=>{let b=document.createElement('button');b.type='button';b.className='stylebtn';b.dataset.style=id;b.innerHTML=`<i aria-hidden="true">${icon}</i>${name}`;b.onclick=()=>{state.style=id;refresh()};$('styles').append(b)});PALETTES.forEach((p,i)=>{let b=document.createElement('button');b.type='button';b.className='palette';b.dataset.index=i;b.setAttribute('aria-label',`Palette ${i+1}`);b.style.background=`linear-gradient(135deg,${p.join(',')})`;b.onclick=()=>{state.colors=[...p];refresh()};$('palettes').append(b)});for(let i=1;i<=3;i++)$('color'+i).addEventListener('input',e=>{state.colors[i-1]=e.target.value;refresh()});$('preset').onchange=e=>{state.preset=e.target.value;if(state.preset!=='custom'){[state.width,state.height]=state.preset.split('x').map(Number)}refresh()};for(let k of ['width','height'])$(k).addEventListener('change',e=>{state[k]=Math.min(7680,Math.max(256,Number(e.target.value)||256));refresh()});for(let k of ['detail','glow','rotation'])$(k).addEventListener('input',e=>{state[k]=+e.target.value;refresh()});$('refresh').onclick=newSeed;$('shuffle').onclick=()=>{state.style=STYLES[Math.floor(Math.random()*STYLES.length)][0];state.colors=[...PALETTES[Math.floor(Math.random()*PALETTES.length)]];state.seed=Math.floor(Math.random()*4294967295);refresh()};$('reset').onclick=()=>{state={...DEFAULT,colors:[...DEFAULT.colors]};refresh();toast('Defaults restored')};$('save').onclick=()=>{try{let list=JSON.parse(localStorage.getItem('wallpaper-studio-saves')||'[]');list.unshift({...state,colors:[...state.colors]});localStorage.setItem('wallpaper-studio-saves',JSON.stringify(list.slice(0,12)));loadHistory();toast('Design saved on this device')}catch{toast('Local storage unavailable')}};$('copy').onclick=async()=>{let str=JSON.stringify(state);try{await navigator.clipboard.writeText(str);toast('Settings copied to clipboard')}catch{toast('Clipboard unavailable: use HTTPS')}};document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>exportWallpaper(b.dataset.format));loadHistory();refresh();if('serviceWorker' in navigator && location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});}
function loadHistory(){let list=[];try{list=JSON.parse(localStorage.getItem('wallpaper-studio-saves')||'[]')}catch{}let wrap=$('history');wrap.replaceChildren();if(!list.length){let t=document.createElement('span');t.className='empty';t.textContent='No saved designs yet';wrap.append(t);return}list.forEach((s,i)=>{let b=document.createElement('button');b.type='button';b.title=`Restore design ${i+1}: ${s.style}`;b.setAttribute('aria-label',b.title);b.style.background=`linear-gradient(135deg,${s.colors.join(',')})`;b.onclick=()=>{state={...s,colors:[...s.colors]};refresh();toast('Design restored')};wrap.append(b)})}
async function exportWallpaper(format){let [w,h]=size();const pixels=w*h;if(pixels>32000000){toast('Resolution too large for safe browser export (max 32 MP)');return}let buttons=document.querySelectorAll('[data-format]');buttons.forEach(b=>b.disabled=true);$('status').textContent='Rendering full resolution…';await new Promise(r=>setTimeout(r,45));try{let out=document.createElement('canvas');out.width=w;out.height=h;draw(out,state);let mime=format==='jpeg'?'image/jpeg':`image/${format}`;let blob=await new Promise(resolve=>out.toBlob(resolve,mime,.94));if(!blob)throw new Error('Export not supported');let link=document.createElement('a');let url=URL.createObjectURL(blob);link.href=url;link.download=`wallpaper-${state.style}-${w}x${h}-${state.seed}.${format==='jpeg'?'jpg':format}`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);toast('Wallpaper downloaded')}catch(err){console.error(err);toast('Export failed: try smaller size or another format')}finally{buttons.forEach(b=>b.disabled=false);$('status').textContent='Ready'}}
document.addEventListener('DOMContentLoaded',init);
