/* Wallpaper Studio v4.2 Final — private local-first user interface. No dependencies. */
(function () {
  'use strict';
  const E=window.WallpaperEngine;
  if(!E)throw new Error('Wallpaper engine is missing');
  const $=id=>document.getElementById(id);
  const by=(sel,root=document)=>[...root.querySelectorAll(sel)];
  const KEYS={recent:'ws4.recent',favorites:'ws4.favorites',device:'ws4.device',clock:'ws4.clock'};
  const DEFAULT={...E.defaults};
  let state={...DEFAULT},recent=[],favorites=[],view='recent',showAdvanced=false,showTune=false,device='android',showClock=true,variations=[];
  let toastTimer=0,renderFrame=0,selectedThumbNodes={},isExporting=false;
  const phoneFormats={android:{w:1080,h:2400,name:'ANDROID PHONE'},iphone:{w:1290,h:2796,name:'IPHONE'}};
  function storageRead(k,fall){try{const data=JSON.parse(localStorage.getItem(k));return data??fall}catch{return fall}}
  function storageWrite(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
  function parseDesign(s){if(!s||typeof s!=='object')return null;const out={...DEFAULT};const styles=E.styles.map(x=>x.id),palettes=E.palettes.map(x=>x.id);if(styles.includes(s.style))out.style=s.style;if(palettes.includes(s.palette))out.palette=s.palette;if(['dark','light'].includes(s.mode))out.mode=s.mode;for(const key of ['seed','layers','curve','height','detail','glow']){if(Number.isFinite(Number(s[key]))){let a=Number(s[key]);out[key]=key==='seed'?Math.abs(Math.floor(a))%2147483647:Math.round(Math.max(key==='layers'?3:0,Math.min(key==='layers'?12:100,a)))}}return out}
  function serialize(s){return [s.style,s.palette,s.mode,s.seed,s.layers,s.curve,s.height,s.detail,s.glow].join('|')}
  function activeStyle(){return E.styles.find(s=>s.id===state.style)||E.styles[0]}
  function notify(text){const box=$('toast');box.textContent=text;box.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.hidden=true,2800)}
  function newSeed(){if(window.crypto?.getRandomValues){let x=new Uint32Array(1);crypto.getRandomValues(x);return x[0]%2147483647}return Math.floor(Math.random()*2147483647)}
  function record(){const item={...state};recent=recent.filter(x=>serialize(x)!==serialize(item));recent.unshift(item);recent=recent.slice(0,18);storageWrite(KEYS.recent,recent);renderCollection()}
  function setDesign(patch,{save=true,refreshThumbs=false}={}){state=parseDesign({...state,...patch})||{...DEFAULT};schedulePreview();syncControls();if(refreshThumbs)renderPatternThumbnails();if(save)record()}
  function drawCanvas(canvas,conf,width,height){canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{alpha:false});E.draw(ctx,width,height,conf)}
  function schedulePreview(){if(renderFrame)return;renderFrame=requestAnimationFrame(()=>{renderFrame=0;drawCanvas($('desktopCanvas'),state,800,450);const fmt=phoneFormats[device];const phoneWidth=330;drawCanvas($('phoneCanvas'),state,phoneWidth,Math.round(phoneWidth*fmt.h/fmt.w));applyClockColors()})}
  function syncControls(){const selected=serialize(state);$('paletteName').textContent=(E.palettes.find(p=>p.id===state.palette)||E.palettes[0]).name;by('.palette-swatch').forEach(btn=>{let chosen=btn.dataset.palette===state.palette;btn.classList.toggle('selected',chosen);btn.setAttribute('aria-pressed',String(chosen))});by('.pattern-button').forEach(btn=>{const selected=btn.dataset.style===state.style;btn.classList.toggle('selected',selected);btn.setAttribute('aria-pressed',String(selected))});for(const [id,mode] of [['darkMode','dark'],['lightMode','light']]){$(id).classList.toggle('selected',state.mode===mode);$(id).setAttribute('aria-pressed',String(state.mode===mode))}const fav=favorites.some(x=>serialize(x)===selected);$('favoriteButton').classList.toggle('is-favorite',fav);$('favoriteIcon').textContent=fav?'♥':'♡';$('favoriteText').textContent=fav?'Saved':'Save design';by('[data-control]').forEach(slider=>{const key=slider.dataset.control;slider.value=state[key];$(key+'Output').textContent=(key==='layers'?state[key]:state[key]+'%')});$('favoriteCount').textContent=String(favorites.length)}
  function applyClockColors(){const invert=state.mode==='light' && !['amoled','aurora'].includes(state.style);by('.lock-overlay').forEach(el=>el.classList.toggle('inverted',invert))}
  function renderPatternThumbnails(){by('.pattern-button').forEach(btn=>{const canvas=btn.querySelector('canvas');drawCanvas(canvas,{...state,style:btn.dataset.style,seed:state.seed},240,135)})}
  function makePattern(s){const button=document.createElement('button');button.type='button';button.className='pattern-button';button.dataset.style=s.id;button.setAttribute('aria-label',s.label+' wallpaper style');button.setAttribute('aria-pressed','false');const canvas=document.createElement('canvas');canvas.className='pattern-thumb';canvas.width=240;canvas.height=135;canvas.setAttribute('aria-hidden','true');const label=document.createElement('span');label.className='pattern-label';label.textContent=s.label;const sub=document.createElement('span');sub.className='pattern-subtitle';sub.textContent=s.subtitle;button.append(canvas,label,sub);button.onclick=()=>{setDesign({style:s.id},{refreshThumbs:false});notify(s.label+' selected')};return button}
  function setupPatterns(){for(const s of E.styles){const parent=s.category==='advanced'?$('advancedGrid'):$('patternGrid');parent.append(makePattern(s))}renderPatternThumbnails();$('advancedToggle').onclick=()=>{showAdvanced=!showAdvanced;$('advancedGrid').hidden=!showAdvanced;$('advancedChevron').textContent=showAdvanced?'−':'＋';$('advancedToggle').setAttribute('aria-expanded',String(showAdvanced))}}
  function setupPalettes(){for(const palette of E.palettes){const button=document.createElement('button');button.className='palette-swatch';button.type='button';button.style.setProperty('--swatch',palette.swatch);button.dataset.palette=palette.id;button.title=palette.name;button.setAttribute('aria-label',palette.name+' palette');button.setAttribute('aria-pressed','false');button.onclick=()=>setDesign({palette:palette.id},{refreshThumbs:true});$('paletteGrid').append(button)}}
  function setupSliders(){const sliders=[['layers','Layers',3,12],['curve','Curvature',0,100],['height','Artwork height',0,100],['detail','Fine detail',0,100],['glow','Glow (extra styles)',0,100]];for(const [key,label,min,max] of sliders){const wrap=document.createElement('div');wrap.className='tune-item';const lab=document.createElement('label');lab.className='tune-label';lab.htmlFor='range-'+key;lab.append(document.createTextNode(label));const out=document.createElement('output');out.id=key+'Output';lab.append(out);const input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.step=1;input.id='range-'+key;input.dataset.control=key;input.value=state[key];input.addEventListener('input',()=>{state[key]=Number(input.value);out.textContent=key==='layers'?state[key]:state[key]+'%';schedulePreview()});input.addEventListener('change',()=>{record();renderPatternThumbnails()});wrap.append(lab,input);$('tuneGrid').append(wrap)}$('adjustToggle').onclick=()=>{showTune=!showTune;$('detailPanel').hidden=!showTune;$('adjustChevron').textContent=showTune?'−':'＋';$('adjustToggle').setAttribute('aria-expanded',String(showTune))};$('restoreSliders').onclick=()=>setDesign({layers:DEFAULT.layers,curve:DEFAULT.curve,height:DEFAULT.height,detail:DEFAULT.detail,glow:DEFAULT.glow},{refreshThumbs:true})}
  function setupClock(){function tick(){const d=new Date();const date=d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});const time=d.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit',hour12:false});by('.clock-date').forEach(x=>x.textContent=date);by('.clock-time').forEach(x=>x.textContent=time)}tick();setInterval(tick,60000);showClock=storageRead(KEYS.clock,true)!==false;by('.lock-overlay').forEach(x=>x.hidden=!showClock);$('previewToggleText').textContent=showClock?'Clock on':'Clock off';$('previewToggle').setAttribute('aria-pressed',String(showClock));$('previewToggle').onclick=()=>{showClock=!showClock;storageWrite(KEYS.clock,showClock);by('.lock-overlay').forEach(x=>x.hidden=!showClock);$('previewToggleText').textContent=showClock?'Clock on':'Clock off';$('previewToggle').setAttribute('aria-pressed',String(showClock))}}
  function setDevice(d){device=d;storageWrite(KEYS.device,d);const fmt=phoneFormats[d];$('phoneHeader').innerHTML=d==='android'?'ANDROID <span>PHONE</span>':'IPHONE <span>PREVIEW</span>';$('phoneResolution').textContent=fmt.w+' × '+fmt.h+' px';$('downloadPhoneLabel').textContent='DOWNLOAD '+(d==='android'?'ANDROID':'IPHONE');$('downloadPhoneSize').textContent=fmt.w+' × '+fmt.h+' px · PNG';$('deviceToggle').textContent='Switch to '+(d==='android'?'iPhone':'Android')+' ↗';$('phoneFrame').style.aspectRatio=fmt.w+' / '+fmt.h;schedulePreview()}
  async function exportWallpaper(fmt){if(isExporting)return;isExporting=true;const button=$(fmt==='desktop'?'downloadDesktop':'downloadPhone');button.disabled=true;const old=button.innerHTML;try{notify('Preparing high-resolution wallpaper…');await new Promise(resolve=>setTimeout(resolve,55));const sz=fmt==='desktop'?{w:3840,h:2160}:phoneFormats[device];const cv=document.createElement('canvas');cv.width=sz.w;cv.height=sz.h;if(cv.width!==sz.w||cv.height!==sz.h)throw new Error('This resolution is not supported by your device.');const context=cv.getContext('2d',{alpha:false});if(!context)throw Error('Your browser could not create the export canvas.');E.draw(context,sz.w,sz.h,state);let blob=await new Promise((resolve,reject)=>cv.toBlob(b=>b?resolve(b):reject(new Error('Export failed — try another browser.')),'image/png'));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`wallpaper-studio-${state.style}-${state.palette}-${fmt}-${state.seed}.png`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);notify('Wallpaper downloaded · '+sz.w+' × '+sz.h)}catch(err){console.warn('Export error',err);notify(err?.message||'Could not export this wallpaper.')}finally{button.disabled=false;button.innerHTML=old;isExporting=false}}
  function variationSeedList(){const list=new Set();while(list.size<4)list.add(newSeed());return [...list]}
  function showVariations(){const seeds=variationSeedList();const area=$('variationsSection'),grid=$('variationGrid');grid.replaceChildren();variations=seeds.map(seed=>({...state,seed}));for(const conf of variations){const button=document.createElement('button');button.type='button';button.className='variation-button';button.title='Use this variation';button.setAttribute('aria-label','Apply variation '+(variations.indexOf(conf)+1));const canvas=document.createElement('canvas');canvas.width=150;canvas.height=250;canvas.setAttribute('aria-hidden','true');button.append(canvas);drawCanvas(canvas,conf,150,250);button.onclick=()=>{setDesign(conf,{refreshThumbs:true});area.hidden=true;notify('Variation applied')};grid.append(button)}area.hidden=false;area.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'})}
  function renderCollection(){const grid=$('historyGrid');grid.replaceChildren();const items=view==='recent'?recent:favorites;for(const conf of items){const b=document.createElement('button');b.type='button';b.className='history-card';b.title='Restore '+conf.style+' design';b.setAttribute('aria-label','Restore '+conf.style+' '+conf.palette+' wallpaper');if(serialize(conf)===serialize(state))b.classList.add('selected');const canvas=document.createElement('canvas');canvas.width=130;canvas.height=190;canvas.setAttribute('aria-hidden','true');drawCanvas(canvas,conf,130,190);const name=document.createElement('span');name.textContent=(E.styles.find(x=>x.id===conf.style)||{}).label||conf.style;b.append(canvas,name);b.onclick=()=>{setDesign(conf,{refreshThumbs:true});notify('Design restored');document.querySelector('.previews').scrollIntoView({behavior:'smooth',block:'start'})};grid.append(b)}if(!items.length){const empty=document.createElement('div');empty.className='empty-collection';empty.textContent=view==='recent'?'Your recent wallpapers will appear here.':'No favorites yet — tap ♡ to save a wallpaper.';grid.append(empty)}$('recentTab').classList.toggle('active',view==='recent');$('favoritesTab').classList.toggle('active',view==='favorites');$('favoriteCount').textContent=String(favorites.length)}
  function toggleFavorite(){const key=serialize(state);const exists=favorites.some(s=>serialize(s)===key);if(exists){favorites=favorites.filter(s=>serialize(s)!==key);notify('Removed from favorites')}else{favorites.unshift({...state});favorites=favorites.slice(0,30);notify('Saved to favorites ♡')}storageWrite(KEYS.favorites,favorites);syncControls();renderCollection()}
  function parseURL(){const q=new URLSearchParams(location.search);if(!q.has('style'))return null;const design={};for(const key of Object.keys(DEFAULT))if(q.has(key))design[key]=q.get(key);return parseDesign(design)}
  function shareURL(){const u=new URL(location.href);for(const [k,v] of Object.entries(state))u.searchParams.set(k,String(v));return u.toString()}
  async function shareDesign(){let url=shareURL();try{if(navigator.share){await navigator.share({title:'Wallpaper Studio design',text:'Try this wallpaper design:',url});return}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(url);notify('Design link copied');return}window.prompt('Copy your design link:',url)}catch(e){if(e?.name!=='AbortError')notify('Sharing unavailable on this browser')}}
  function setPageTheme(theme){
    const dark=theme==='dark';
    document.documentElement.dataset.theme=dark?'dark':'light';
    document.documentElement.style.colorScheme=dark?'dark':'light';
    const meta=$('browserThemeColor');if(meta)meta.content=dark?'#111418':'#f4f4f2';
    const button=$('pageThemeButton');
    button.setAttribute('aria-pressed',String(dark));
    button.title=dark?'Switch to light page theme':'Switch to dark page theme';
    button.setAttribute('aria-label',button.title);
    $('pageThemeIcon').innerHTML=dark?'<path d="M20 15.4A8.4 8.4 0 0 1 8.6 4a8.5 8.5 0 1 0 11.4 11.4Z"/>':'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>';
    try{localStorage.setItem('ws4.pageTheme',dark?'dark':'light')}catch{}
  }
  function setupEvents(){$('homeButton').onclick=()=>{setDesign({...DEFAULT},{refreshThumbs:true});notify('Back to the starting design')};$('pageThemeButton').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';setPageTheme(next);notify(next==='dark'?'Dark page theme':'Light page theme')};$('darkMode').onclick=()=>setDesign({mode:'dark'},{refreshThumbs:true});$('lightMode').onclick=()=>setDesign({mode:'light'},{refreshThumbs:true});$('generateButton').onclick=()=>setDesign({seed:newSeed()},{refreshThumbs:true});$('variationsButton').onclick=showVariations;$('downloadDesktop').onclick=()=>exportWallpaper('desktop');$('downloadPhone').onclick=()=>exportWallpaper('phone');$('deviceToggle').onclick=()=>setDevice(device==='android'?'iphone':'android');$('favoriteButton').onclick=toggleFavorite;$('recentTab').onclick=()=>{view='recent';renderCollection()};$('favoritesTab').onclick=()=>{view='favorites';renderCollection()};$('shareButton').onclick=shareDesign;$('clearHistory').onclick=()=>{if(!recent.length)return notify('No history to clear');if(window.confirm('Clear your recent wallpaper history? Favorites will remain saved.')){recent=[];storageWrite(KEYS.recent,recent);renderCollection();notify('Recent history cleared')}}}
  function init(){const stored=storageRead(KEYS.recent,[]),saved=storageRead(KEYS.favorites,[]);recent=Array.isArray(stored)?stored.map(parseDesign).filter(Boolean).slice(0,18):[];favorites=Array.isArray(saved)?saved.map(parseDesign).filter(Boolean).slice(0,30):[];const urlState=parseURL();state=urlState||recent[0]||{...DEFAULT};const oldDevice=storageRead(KEYS.device,'android');device=oldDevice==='iphone'?'iphone':'android';setupPatterns();setupPalettes();setupSliders();setupClock();setupEvents();let pageTheme='light';try{pageTheme=localStorage.getItem('ws4.pageTheme')==='dark'?'dark':'light'}catch{}setPageTheme(pageTheme);setDevice(device);syncControls();renderPatternThumbnails();record();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
  init();
})();
